#
# YAML template that can be extended for CI builds for dotnet projects.
# Since resources cannot be declared in templates, this template requires the top-level
# YAML pipeline file to create the PipelineAutomation respository resource, for example:
#
# resources:
#  repositories:
#    - repository: PipelineAutomation
#      type: git
#      name: 'Apollo/PipelineAutomation'
#

parameters:
    # Optional: Filter for the projects to build.
  - name: projectsToBuild
    default: '**/*.csproj'

    # Optional: Filter for the test projects. Defaults to naming convention [name].Tests.csproj.
  - name: projectsToTest
    default: '**/*.[Tt]ests.csproj'

    # Optional: Path to the NuGet.config file for dotnet restore.
  - name: nugetConfigPath
    default: NuGet.config

    # Optional: The artifact feed guid to use instead of NuGet.config defined with nugetConfigPath.
  - name: nugetFeed
    default: ''

    # Optional: The build agent pool.
  - name: buildPool
    default: GEICO Linux Pool

    # Optional: Demands for the build agent pool.
  - name: buildPoolDemands
    type: object
    default: []

    # Optional: The project build configuration to use.
  - name: buildConfiguration
    default: Release

stages:
- stage: BuildAndTest
  displayName: 'Build and Test'
  pool:
    name: ${{ parameters.buildPool }}
    demands: ${{ parameters.buildPoolDemands }}
  jobs:
  - job: BuildAndTest
    displayName: 'Build and Test'
    workspace:
      clean: all
    steps:
    - checkout: self
      clean: true
    - template: ./dotnet-build-steps.yml
      parameters:
        projectsToBuild: ${{ parameters.projectsToBuild }}
        projectsToTest: ${{ parameters.projectsToTest }}
        buildConfiguration: ${{ parameters.buildConfiguration }}
        nugetConfigPath:  ${{ parameters.nugetConfigPath }}
        nugetFeed:  ${{ parameters.nugetFeed }}
